pipeline {
    agent any
    stages {
        stage('test Forjfile') {
            steps {
                sh('''VERSION=latest
                wget -O ./forjj https://github.com/forj-oss/forjj/releases/download/$VERSION/forjj
                chmod +x .forjj
                ./forjj validate
                rm -f forjj
                ''')
            }
        }
    }
}
