// This file is autogenerated by "go generate". Do not modify it.
// It has been generated from your 'github.yaml' file.
// To update those structure, update the 'github.yaml' and run 'go generate'
package main

// ************************
// Create request structure
// ************************

type CreateReq struct {
	Forj struct {
		Debug string `json:"debug"`
		ForjjInstanceName string `json:"forjj-instance-name"`
		ForjjSourceMount string `json:"forjj-source-mount"`
	}
	Objects CreateArgReq
}

type CreateArgReq struct {
	App map[string]AppInstanceStruct `json:"app"` // Object details
	Group map[string]GroupInstanceStruct `json:"group"` // Object details
	Repo map[string]RepoInstanceStruct `json:"repo"` // Object details
	User map[string]UserInstanceStruct `json:"user"` // Object details
}

type AppInstanceStruct struct {
	Add AppAddStruct
	Change AppChangeStruct
	List AppListStruct
	Remove AppRemoveStruct
	Rename AppRenameStruct
}

type GroupInstanceStruct struct {
	Add GroupAddStruct
	Change GroupChangeStruct
	List GroupListStruct
	Remove GroupRemoveStruct
	Rename GroupRenameStruct
}

type RepoInstanceStruct struct {
	Add RepoAddStruct
	Change RepoChangeStruct
}

type UserInstanceStruct struct {
	Add UserAddStruct
	Change UserChangeStruct
	List UserListStruct
	Remove UserRemoveStruct
	Rename UserRenameStruct
}


type AppAddStruct struct {
	ForjjInfra string // Name of the Infra repository to use in github if requested.
	ForjjOrganization string // Default FORJJ Organization. Used by default as github organization. If you want different one, use --github-organization
	Organization string // Github Organization name. By default, it uses the FORJJ organization name
	Server string // Github Entreprise Server name. By default, public 'github.com' API is used.
	Token string // github token to access. This token must authorize organization level access.
}

type AppChangeStruct struct {
	ForjjInfra string // Name of the Infra repository to use in github if requested.
	Server string // Github Entreprise Server name. By default, public 'github.com' API is used.
	Token string // github token to access. This token must authorize organization level access.
}

type AppListStruct struct {
	Server string // Github Entreprise Server name. By default, public 'github.com' API is used.
}

type AppRemoveStruct struct {
	Server string // Github Entreprise Server name. By default, public 'github.com' API is used.
}

type AppRenameStruct struct {
	Server string // Github Entreprise Server name. By default, public 'github.com' API is used.
}

type GroupAddStruct struct {
	Name string // group name
	Organization string // To manage github teams at organization level
	RemoveUsers string // remove users from github team.
	Roles string // List of roles to apply to the new group.
	Users string // List of users to attach to the new group.
}

type GroupChangeStruct struct {
	AddRoles string // Roles added to the group.
	AddUsers string // Add users to github team.
	Name string // group name
	Organization string // To manage github teams at organization level
	RemoveRoles string // Roles removed to the group.
	RemoveUsers string // remove users from github team.
}

type GroupListStruct struct {
	Name string // group name
	Organization string // To manage github teams at organization level
	RemoveUsers string // remove users from github team.
}

type GroupRemoveStruct struct {
	Name string // group name
	Organization string // To manage github teams at organization level
	RemoveUsers string // remove users from github team.
}

type GroupRenameStruct struct {
	Name string // group name
	Organization string // To manage github teams at organization level
	RemoveUsers string // remove users from github team.
}

type RepoAddStruct struct {
	Flow string // Flow activated on this repository
	ForjjWorkspaceMount string // Where the workspace dir is located in the github plugin container.
	Groups string // List of groups (group:role) to attach to the repository, separated by comma.
	Name string // Repository name
	Title string // Github Repository title
	Users string // List of users (user:role) to attach to the repository, separated by comma.
}

type RepoChangeStruct struct {
	AddGroups string // List of additional groups (group:role) to attach to the repository, separated by comma.
	AddUsers string // List of additional users (user:role) to attach to the repository, separated by comma.
	Flow string // Flow activated on this repository
	ForjjWorkspaceMount string // Where the workspace dir is located in the github plugin container.
	Name string // Repository name
	Title string // Github Repository title
}

type UserAddStruct struct {
	Name string // 
	Organization string // To manage github users at organization level
	Roles string // 
}

type UserChangeStruct struct {
	AddRoles string // 
	Name string // 
	Organization string // To manage github users at organization level
	RemoveRoles string // Roles removed from the user.
}

type UserListStruct struct {
	Name string // 
	Organization string // To manage github users at organization level
}

type UserRemoveStruct struct {
	Name string // 
	Organization string // To manage github users at organization level
}

type UserRenameStruct struct {
	Name string // 
	Organization string // To manage github users at organization level
}


// ************************
// Update request structure
// ************************

type UpdateReq struct {
	Forj struct {
		Debug string `json:"debug"`
		ForjjInstanceName string `json:"forjj-instance-name"`
		ForjjSourceMount string `json:"forjj-source-mount"`
	}
	Objects UpdateArgReq
}

type UpdateArgReq struct {
	App map[string]AppInstanceStruct `json:"app"` // Object details
	Group map[string]GroupInstanceStruct `json:"group"` // Object details
	Repo map[string]RepoInstanceStruct `json:"repo"` // Object details
	User map[string]UserInstanceStruct `json:"user"` // Object details
}

// **************************
// Maintain request structure
// **************************

type MaintainReq struct {
	Forj struct {
		Debug string `json:"debug"`
		ForjjInstanceName string `json:"forjj-instance-name"`
		ForjjSourceMount string `json:"forjj-source-mount"`
		ForjjWorkspaceMount string `json:"forjj-workspace-mount"`
	}
	Objects MaintainArgReq
}

type MaintainArgReq struct {
	App map[string]AppMaintainStruct `json:"app"` // Object details
}

type AppMaintainStruct struct {
	Setup struct {
		Token string // github token to access. This token must authorize organization level access.
	}
}


// YamlDesc has been created from your 'github.yaml' file.
const YamlDesc = "---\n" +
   "plugin: \"github\"\n" +
   "version: \"0.1\"\n" +
   "description: \"Upstream github plugin for FORJJ. It properly configure github.com or entreprise with organisation/repos\"\n" +
   "runtime:\n" +
   "  docker:\n" +
   "    image: \"hub.docker.hpecorp.net/devops/forjj-github\"\n" +
   "  service_type: \"REST API\"\n" +
   "  service:\n" +
   "    parameters: [ \"service\", \"start\" ]\n" +
   "created_flag_file: \"{{ .InstanceName }}/{{.Name}}.yaml\"\n" +
   "task_flags: # All task flags will be delivered by forjj to the plugin under forj/\n" +
   "  common:\n" +
   "    debug:\n" +
   "      help: \"To activate github debug information\"\n" +
   "    forjj-source-mount:\n" +
   "      help: \"Where the source dir is located for github plugin container.\"\n" +
   "    forjj-instance-name:\n" +
   "       help: \"Name of the jenkins instance given by forjj.\"\n" +
   "  maintain:\n" +
   "    forjj-workspace-mount:\n" +
   "      help: \"Where the workspace dir is located in the github plugin container.\"\n" +
   "objects: # All objects will be delivered by forjj except workspace/infra under objects/<type>/<instance>/<action>/key=value\n" +
   "  # Define infra object special flag for github\n" +
   "  app: # already defined by Forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\"] No need to define it.\n" +
   "    flags:\n" +
   "      server:\n" +
   "        help: \"Github Entreprise Server name. By default, public 'github.com' API is used.\"\n" +
   "      forjj-organization:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"Default FORJJ Organization. Used by default as github organization. If you want different one, use --github-organization\"\n" +
   "      organization:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"Github Organization name. By default, it uses the FORJJ organization name\"\n" +
   "      forjj-infra:\n" +
   "        only-for-actions: [\"add\", \"change\"]\n" +
   "        help: \"Name of the Infra repository to use in github if requested.\"\n" +
   "      token:\n" +
   "        only-for-actions: [\"add\", \"change\"]\n" +
   "        help: \"github token to access. This token must authorize organization level access.\"\n" +
   "        required: true\n" +
   "        secure: true\n" +
   "        envar: \"TOKEN\"\n" +
   "  # Define github group exposure to forjj\n" +
   "  group: # New object type in forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\", \"list\", \"rename\"]\n" +
   "    help: \"Manage teams in github\"\n" +
   "    identified_by_flag: name\n" +
   "    flags:\n" +
   "      organization:\n" +
   "        help: \"To manage github teams at organization level\"\n" +
   "        default: \"false\"\n" +
   "      users:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of users to attach to the new group.\"\n" +
   "      add-users:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"Add users to github team.\"\n" +
   "      remove-users:\n" +
   "        actions: [\"change\"]\n" +
   "        help: \"remove users from github team.\"\n" +
   "      name:\n" +
   "        help: \"group name\"\n" +
   "        required: true\n" +
   "      roles:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of roles to apply to the new group.\"\n" +
   "      add-roles:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"Roles added to the group.\"\n" +
   "      remove-roles:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"Roles removed to the group.\"\n" +
   "  # Define github users exposure to forjj\n" +
   "  user: # New object type in forjj\n" +
   "    # Default is : actions: [\"add\", \"change\", \"remove\", \"list\", \"rename\"]\n" +
   "    help: \"Manage teams in github\"\n" +
   "    identified_by_flag: name\n" +
   "    flags:\n" +
   "      organization:\n" +
   "        help: \"To manage github users at organization level\"\n" +
   "        default: \"false\"\n" +
   "      name:\n" +
   "        options:\n" +
   "          help: \"user name\"\n" +
   "          required: true\n" +
   "      roles:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        options:\n" +
   "          help: \"List of roles to apply to the new user.\"\n" +
   "      add-roles:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        options:\n" +
   "          help: \"Roles added to the user.\"\n" +
   "      remove-roles:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"Roles removed from the user.\"\n" +
   "  repo: # Enhance Forjj repo object\n" +
   "    actions: [\"add\", \"change\"]\n" +
   "    flags:\n" +
   "      name:\n" +
   "        help: \"Repository name\"\n" +
   "      title:\n" +
   "        help: \"Github Repository title\"\n" +
   "      users:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of users (user:role) to attach to the repository, separated by comma.\"\n" +
   "      groups:\n" +
   "        only-for-actions: [\"add\"]\n" +
   "        help: \"List of groups (group:role) to attach to the repository, separated by comma.\"\n" +
   "      add-users:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"List of additional users (user:role) to attach to the repository, separated by comma.\"\n" +
   "      add-groups:\n" +
   "        only-for-actions: [\"change\"]\n" +
   "        help: \"List of additional groups (group:role) to attach to the repository, separated by comma.\"\n" +
   "      flow:\n" +
   "        help: \"Flow activated on this repository\"\n" +
   "      forjj-workspace-mount:\n" +
   "        help: \"Where the workspace dir is located in the github plugin container.\"\n" +
   ""
