// This file is autogenerated by "go generate". Do not modify it.
// It has been generated from your 'github.yaml' file.
// To update those structure, update the 'github.yaml' and run 'go generate'
package main

// Object app groups structure

// Groups structure


// Object Instance structures

type AppInstanceStruct struct {
	ForjjInfra 